### ISSUE TITLE
Pronouns

### ISSUE THREAD

**Issue by lefeuil** [Connor800/CyberLife-docs#6]
### Abstract

The current profile format for new members requires a 'Gender' field to be filled. This can be uncomfortable for some to answer, so I suggest replacing this field with 'preferred pronouns' instead. 
By making it an open field, this will make profiles easier to fill and avoid discomfort for new members. 

### Description

This question would replace the prompt for 'gender' entirely. It should provide an example to avoid confusion. 
One way to phrase the question might be: "What are your preferred pronouns? As Chloe, mine are she/her." 
it should be an open field so that any typos or changes in formatting are still accepted (ex. "she her", "she", "she-her" wouldn't stop the process). Optionally, Chloe could reply with "I'll be sure to refer to you as [pronouns]." This isn't necessary. 

### Context

Several new members have reached out via DMs to ask about this question and how they should answer. Additionally, it can be disheartening for anyone who is questioning their identity and provide a false idea of the community we have. 

### Checklist

- [x] I have searched the open issues for duplicates.

**Comment by DanLCD** [comment]
Rebased on the rewrite branch. I'll close this for now.
